runtime: go
api_version: go1
handlers:
- url: /oauth
  script: _go_app
- url: /init
  script: _go_app
- url: /five
  script: _go_app
- url: /
  static_files: www/index.html
  upload: www/index.html
- url: /(.*)
  static_files: www/\1
  upload: www/assets/(.*)
